In [2]:
import pandas as pd

In [3]:
claimants_df = pd.read_csv('claimants.csv')
claimants_df

      CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0           5         0     0.0       1.0       0.0    50.0  34.940
1           3         1     1.0       0.0       0.0    18.0   0.891
2          66         1     0.0       1.0       0.0     5.0   0.330
3          70         0     0.0       1.0       1.0    31.0   0.037
4          96         1     0.0       1.0       0.0    30.0   0.038
...       ...       ...     ...       ...       ...     ...     ...
1335    34100         1     0.0       1.0       0.0     NaN   0.576
1336    34110         0     1.0       1.0       0.0    46.0   3.705
1337    34113         1     1.0       1.0       0.0    39.0   0.099
1338    34145         0     1.0       0.0       0.0     8.0   3.177
1339    34153         1     1.0       1.0       0.0    30.0   0.688

[1340 rows x 7 columns]

In [4]:
claimants_df.shape

(1340, 7)

In [5]:
claimants_df.isna().sum()

CASENUM       0
ATTORNEY      0
CLMSEX       12
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [6]:
claimants_df.dtypes

CASENUM       int64
ATTORNEY      int64
CLMSEX      float64
CLMINSUR    float64
SEATBELT    float64
CLMAGE      float64
LOSS        float64
dtype: object

In [7]:
claimants_df.dropna(inplace=True)

In [8]:
claimants_df

      CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0           5         0     0.0       1.0       0.0    50.0  34.940
1           3         1     1.0       0.0       0.0    18.0   0.891
2          66         1     0.0       1.0       0.0     5.0   0.330
3          70         0     0.0       1.0       1.0    31.0   0.037
4          96         1     0.0       1.0       0.0    30.0   0.038
...       ...       ...     ...       ...       ...     ...     ...
1334    34104         1     1.0       1.0       0.0    16.0   0.060
1336    34110         0     1.0       1.0       0.0    46.0   3.705
1337    34113         1     1.0       1.0       0.0    39.0   0.099
1338    34145         0     1.0       0.0       0.0     8.0   3.177
1339    34153         1     1.0       1.0       0.0    30.0   0.688

[1096 rows x 7 columns]

In [9]:
X = claimants_df[['CLMSEX', 'CLMINSUR', 'SEATBELT', 'LOSS']]

In [10]:
y = claimants_df['ATTORNEY']

In [11]:
X

      CLMSEX  CLMINSUR  SEATBELT    LOSS
0        0.0       1.0       0.0  34.940
1        1.0       0.0       0.0   0.891
2        0.0       1.0       0.0   0.330
3        0.0       1.0       1.0   0.037
4        0.0       1.0       0.0   0.038
...      ...       ...       ...     ...
1334     1.0       1.0       0.0   0.060
1336     1.0       1.0       0.0   3.705
1337     1.0       1.0       0.0   0.099
1338     1.0       0.0       0.0   3.177
1339     1.0       1.0       0.0   0.688

[1096 rows x 4 columns]

In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [71]:
X_train, X_test, y_train, y_test = train_test_split( X , y ,test_size=0.20, shuffle=True, random_state=42)

In [72]:
logistic_model = LogisticRegression()

In [73]:
logistic_model.fit(X_train,y_train)

LogisticRegression()

In [74]:
y_predicted_train = logistic_model.predict(X_train)

In [75]:
y_predicted_test = logistic_model.predict(X_test)
y_predicted_test

array([1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1])

### Model evaluation

In [76]:
from sklearn.metrics import accuracy_score

In [77]:
accuracy_score(y_train, y_predicted_train)

0.7077625570776256

In [78]:
accuracy_score(y_test, y_predicted_test)

0.6863636363636364

### Deploy

In [79]:
from pickle import dump

In [70]:
dump(logistic_model, open("claimants.pkl",'wb'))